[site]
title = "Yuhang Yan"
description = "PhD student at the University of Example."
favicon = "/favicon.svg"
last_updated = "November 18, 2025"

[author]
name = "Yuhang Yan"
title = "Master's Student"
institution = "The Chinese University of Hong Kong, Shenzhen"
avatar = "/yyh.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "yuhangyan@link.cuhk.edu.cn"
location = "The Chinese University of Hong Kong, Shenzhen"
location_url = "https://www.cuhk.edu.cn"
location_details = [
  "The Chinese University of Hong Kong, Shenzhen"
]
google_scholar = "https://scholar.google.com"
orcid = "https://orcid.org"
github = "https://github.com/Ireliya"
linkedin = "https://www.linkedin.com/in/yuhang-yan-487146283/"

# Visitor map widget (optional)
# Example (ClustrMaps):
# visitor_stats_html = """<script type="text/javascript" id="clustrmaps" src="//cdn.clustrmaps.com/map_v2.js?cl=ffffff&w=a&t=n&d=YOUR_TOKEN"></script>"""
visitor_stats_html = """<script type="text/javascript" id="clustrmaps" src="//clustrmaps.com/map_v2.js?d=a9KRY_y4Z6TnXPkxYwWMFD3qvUnk1gvDopSWX9vJBJw&cl=ffffff&w=a"></script>"""

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "auto"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
