[[news]]
date = "2026-06-10"
content = "Our two papers have been accepted by the [**IFOU**](https://ifou2026.com/) conference, a Class A conference in urban planning."

[[news]]
date = "2025-09-01"
content = "I began my master's journey at The Chinese University of Hong Kong, Shenzhen."
