[site]
title = "鄢宇航"
description = "某某大学博士生个人主页。"
last_updated = "2025年11月18日"

[author]
name = "鄢宇航"
title = "硕士生"
institution = "香港中文大学（深圳）"

[social]
email = "yuhangyan@link.cuhk.edu.cn"
location = "香港中文大学（深圳）"
location_url = "https://www.cuhk.edu.cn"
location_details = [
  "香港中文大学（深圳）"
]
github = "https://github.com/Ireliya"
linkedin = "https://www.linkedin.com/in/yuhang-yan-487146283/"

# 访客地图（可选）
# 示例（ClustrMaps）：
# visitor_stats_html = """<script type="text/javascript" id="clustrmaps" src="//cdn.clustrmaps.com/map_v2.js?cl=ffffff&w=a&t=n&d=YOUR_TOKEN"></script>"""
visitor_stats_html = """<script type="text/javascript" id="clustrmaps" src="https://clustrmaps.com/map_v2.js?d=a9KRY_y4Z6TnXPkxYwWMFD3qvUnk1gvDopSWX9vJBJw&cl=ffffff&w=a"></script>"""

[[navigation]]
title = "关于我"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "论文"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "服务"
type = "page"
target = "services"
href = "/services"
